### PR TITLE
open Browser after end or exit a video

### PR DESCRIPTION
**Pull request by Kronos2308**
* a simple loop to be able to select another video without exit the app

### CODE REVIEW

**Comment by LTVA1** [comment]
Hi, this looks okay but I don't have time to test it right now (I would need to search for recent Unleashed build because I don't want to lose some specific settings on my Flipper, and tracking down the toolchain commit which would still work on old firmware is too long too). Can you post something here when new Unleashed build comes out? It would remind me to accept the PR (and maybe add seeking across the video file, as it is done in wav player)

**Comment by Kronos2308** [comment]
I just add a loop that breaks if press back on file browser
But to keep the code pretty y had to add some tabs 

I just in close the player into a loop and add a exception to break that loop si you play a video and then if finish or you press back then just go to the beginning of the loop and search for another video I use Xtreme firm to compile and test

**Comment by LTVA1** [comment]
Yes, I see, but again, I don't have enough free time to reinstall the firmware and my toolchain to test some edge cases. The PR is correct and valid and I am pretty certain it doesn't add any bugs or whatever, but I will still wait until new Unleashed release because I don't want to lose my Flipper firmware-specific settings.

**Comment by Kronos2308** [comment]
Sure 😊

**Comment by LTVA1** [comment]
Okay, let's try to merge it!

**Comment by LTVA1** [comment]
Yes, it seems to work as intended!

**Pull request merged**
